feat(auth): add testing file - test health route

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -16,12 +16,12 @@ npm run format:check || {
     exit 1
 }
 
-# Run tests
-# echo "\n🧪 Running tests..."
-# npm test || {
-#     echo "❌ Tests failed. Please fix the failing tests and try committing again."
-#     exit 1
-# }
+Run tests
+echo "\n🧪 Running tests..."
+npm test || {
+    echo "❌ Tests failed. Please fix the failing tests and try committing again."
+    exit 1
+}
 
 # If everything passes
 echo "\n✅ All checks passed! Proceeding with commit..."
